// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/call_price/call_price.proto

package call_price

import (
	context "context"
	fmt "fmt"
	base "github.com/CRORCR/cr-common/proto/base"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPriceReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPriceReq) Reset()         { *m = GetPriceReq{} }
func (m *GetPriceReq) String() string { return proto.CompactTextString(m) }
func (*GetPriceReq) ProtoMessage()    {}
func (*GetPriceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a53be7b08ff06e4b, []int{0}
}

func (m *GetPriceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceReq.Unmarshal(m, b)
}
func (m *GetPriceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceReq.Marshal(b, m, deterministic)
}
func (m *GetPriceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceReq.Merge(m, src)
}
func (m *GetPriceReq) XXX_Size() int {
	return xxx_messageInfo_GetPriceReq.Size(m)
}
func (m *GetPriceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceReq proto.InternalMessageInfo

func (m *GetPriceReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetPriceResp struct {
	Data                 []*GetPriceResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *base.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPriceResp) Reset()         { *m = GetPriceResp{} }
func (m *GetPriceResp) String() string { return proto.CompactTextString(m) }
func (*GetPriceResp) ProtoMessage()    {}
func (*GetPriceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a53be7b08ff06e4b, []int{1}
}

func (m *GetPriceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceResp.Unmarshal(m, b)
}
func (m *GetPriceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceResp.Marshal(b, m, deterministic)
}
func (m *GetPriceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceResp.Merge(m, src)
}
func (m *GetPriceResp) XXX_Size() int {
	return xxx_messageInfo_GetPriceResp.Size(m)
}
func (m *GetPriceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceResp proto.InternalMessageInfo

func (m *GetPriceResp) GetData() []*GetPriceResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetPriceResp) GetPagination() *base.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetPriceResp_Data struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPriceResp_Data) Reset()         { *m = GetPriceResp_Data{} }
func (m *GetPriceResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetPriceResp_Data) ProtoMessage()    {}
func (*GetPriceResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a53be7b08ff06e4b, []int{1, 0}
}

func (m *GetPriceResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceResp_Data.Unmarshal(m, b)
}
func (m *GetPriceResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceResp_Data.Marshal(b, m, deterministic)
}
func (m *GetPriceResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceResp_Data.Merge(m, src)
}
func (m *GetPriceResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetPriceResp_Data.Size(m)
}
func (m *GetPriceResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceResp_Data proto.InternalMessageInfo

func (m *GetPriceResp_Data) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetPriceResp_Data) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *GetPriceResp_Data) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*GetPriceReq)(nil), "call_price.GetPriceReq")
	proto.RegisterType((*GetPriceResp)(nil), "call_price.GetPriceResp")
	proto.RegisterType((*GetPriceResp_Data)(nil), "call_price.GetPriceResp.Data")
}

func init() { proto.RegisterFile("proto/call_price/call_price.proto", fileDescriptor_a53be7b08ff06e4b) }

var fileDescriptor_a53be7b08ff06e4b = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xcd, 0x3a, 0x95, 0xbd, 0x7a, 0x18, 0x41, 0x31, 0x14, 0xc4, 0xda, 0x53, 0x2f, 0xa6,
	0xb3, 0xde, 0x3d, 0x6c, 0x83, 0x79, 0x50, 0x1c, 0x39, 0x7a, 0x91, 0xb4, 0x0d, 0x33, 0xb0, 0xf6,
	0x75, 0x6b, 0xfa, 0xb7, 0xf9, 0xef, 0x49, 0x5f, 0xc1, 0x15, 0x75, 0x97, 0xf0, 0xde, 0x97, 0x5f,
	0xde, 0xf7, 0x85, 0x07, 0x77, 0xf5, 0x1e, 0x1d, 0x26, 0xb9, 0xde, 0x6e, 0x3f, 0xea, 0xbd, 0xcd,
	0xcd, 0xa0, 0x94, 0x74, 0xc7, 0xe1, 0xa0, 0x04, 0x57, 0x3d, 0x9e, 0xe9, 0xc6, 0xd0, 0xd1, 0x23,
	0xd1, 0x2d, 0xf8, 0x2b, 0xe3, 0xd6, 0x1d, 0xa2, 0xcc, 0x8e, 0x4f, 0xc1, 0x6b, 0x6d, 0x21, 0x58,
	0xc8, 0xe2, 0x89, 0xea, 0xca, 0xe8, 0x8b, 0xc1, 0xc5, 0x81, 0x68, 0x6a, 0xfe, 0x00, 0xe3, 0x42,
	0x3b, 0x2d, 0x58, 0xe8, 0xc5, 0x7e, 0x7a, 0x23, 0x07, 0xae, 0x43, 0x4e, 0x2e, 0xb5, 0xd3, 0x8a,
	0x50, 0x3e, 0x03, 0xa8, 0xf5, 0xc6, 0x56, 0xda, 0x59, 0xac, 0xc4, 0x28, 0x64, 0xb1, 0x9f, 0x4e,
	0x25, 0xa5, 0x58, 0xff, 0xe8, 0x6a, 0xc0, 0x04, 0x73, 0x18, 0x77, 0xef, 0xff, 0xe6, 0xe1, 0x9c,
	0xec, 0x0d, 0x4d, 0x99, 0xd0, 0x7c, 0xc3, 0x2f, 0xe1, 0x94, 0x02, 0x08, 0x2f, 0x64, 0xf1, 0x48,
	0xf5, 0x4d, 0xfa, 0x0a, 0xfe, 0xb3, 0x6d, 0x96, 0xa6, 0xc4, 0x17, 0xdb, 0x38, 0xfe, 0x04, 0xe7,
	0x2b, 0xe3, 0xba, 0x96, 0x5f, 0xff, 0x1f, 0x7a, 0x17, 0x88, 0x63, 0xbf, 0x89, 0x4e, 0xe6, 0xb3,
	0x77, 0xb9, 0xb1, 0xee, 0xb3, 0xcd, 0x64, 0x8e, 0x65, 0xb2, 0x50, 0x6f, 0x6a, 0xa1, 0x92, 0xa2,
	0x45, 0xbc, 0xcf, 0xb1, 0x2c, 0xb1, 0x4a, 0x7e, 0xef, 0x23, 0x3b, 0x23, 0xe5, 0xf1, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xff, 0x90, 0xed, 0x81, 0xaa, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HisDemoListClient is the client API for HisDemoList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HisDemoListClient interface {
	GetDemo(ctx context.Context, in *GetPriceReq, opts ...grpc.CallOption) (*GetPriceResp, error)
}

type hisDemoListClient struct {
	cc *grpc.ClientConn
}

func NewHisDemoListClient(cc *grpc.ClientConn) HisDemoListClient {
	return &hisDemoListClient{cc}
}

func (c *hisDemoListClient) GetDemo(ctx context.Context, in *GetPriceReq, opts ...grpc.CallOption) (*GetPriceResp, error) {
	out := new(GetPriceResp)
	err := c.cc.Invoke(ctx, "/call_price.HisDemoList/GetDemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HisDemoListServer is the server API for HisDemoList service.
type HisDemoListServer interface {
	GetDemo(context.Context, *GetPriceReq) (*GetPriceResp, error)
}

// UnimplementedHisDemoListServer can be embedded to have forward compatible implementations.
type UnimplementedHisDemoListServer struct {
}

func (*UnimplementedHisDemoListServer) GetDemo(ctx context.Context, req *GetPriceReq) (*GetPriceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDemo not implemented")
}

func RegisterHisDemoListServer(s *grpc.Server, srv HisDemoListServer) {
	s.RegisterService(&_HisDemoList_serviceDesc, srv)
}

func _HisDemoList_GetDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisDemoListServer).GetDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/call_price.HisDemoList/GetDemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisDemoListServer).GetDemo(ctx, req.(*GetPriceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HisDemoList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "call_price.HisDemoList",
	HandlerType: (*HisDemoListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDemo",
			Handler:    _HisDemoList_GetDemo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/call_price/call_price.proto",
}
